name = "VeIR"
version = "0.1.0"
defaultTargets = ["veir-opt", "veir-interpret", "run-benchmarks", "veir2mir", "Veir"]
testRunner = "UnitTest"
buildType = "release"
moreLeanArgs = ["--tstack=400000"]
moreServerArgs = ["--tstack=400000"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "ExArray"
path = "ExArray"

[[lean_lib]]
name = "Veir"
root = "Veir"

[[lean_lib]]
name = "UnitTest"
root = "UnitTest"

[[lean_exe]]
name = "veir-opt"
root = "VeirOpt"

[[lean_exe]]
name = "run-benchmarks"
root = "RunBenchmarks"

[[lean_exe]]
name = "veir-interpret"
root = "VeirInterpret"

[[lean_exe]]
name = "veir2mir"
root = "VeirToMIR"
