name = "VeIR"
version = "0.1.0"
defaultTargets = ["veir-opt", "veir-interpret", "run-benchmarks", "Veir"]
testRunner = "UnitTest"
moreLeanArgs = ["--tstack=400000"]
moreServerArgs = ["--tstack=400000"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#8205572479d035c46e07ed4c9888745ca603e82c"

[[require]]
name = "ExArray"
path = "ExArray"

[[lean_lib]]
name = "Veir"
root = "Veir"

[[lean_lib]]
name = "UnitTest"
root = "UnitTest"

[[lean_exe]]
name = "veir-opt"
root = "VeirOpt"

[[lean_exe]]
name = "run-benchmarks"
root = "RunBenchmarks"

[[lean_exe]]
name = "veir-interpret"
root = "VeirInterpret"
