module

import Veir.Interfaces.DataLayoutInterfaces
import Veir.Interfaces.FoldInterfaces
import Veir.Interfaces.FunctionInterfaces
import Veir.Interfaces.RegionKindInterfaces
import Veir.Interfaces.SideEffectInterfaces
import Veir.Interfaces.DeadCodeInterfaces
import Veir.Interfaces.ConstantLikeInterfaces
import Veir.Interfaces.ControlFlowInterfaces
