module

-- AUTOGENERATED Veir file: Automated GlobalISel pattern translation from llvm-project/llvm/include/llvm/Target/GlobalISel/Combine.td. Commit c86dd0703982b39cacf12cd044ab9735f31d1e1d

public import Veir.Passes.Matching
public import Veir.PatternRewriter.Basic
public import Veir.GlobalOpInfo

public section

namespace Veir.RISCV

def sub_minus_one_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, op1, _props) := matchSub op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal lhs ctx.raw | return (ctx, none)
  if cst.value ≠ -1 then return (ctx, none)
  let .integerType ctype := (op1.getType! ctx.raw).val | return (ctx, none)
  let cstOpProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (-1) ctype))
  let (ctx, cstOp) ← WfRewriter.createOp! ctx Llvm.mlir__constant #[op1.getType! ctx.raw] #[]
    #[] #[] cstOpProp none
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.xor #[op1.getType! ctx.raw] #[op1, (cstOp.getResult 0)]
    #[] #[] () none
  some (ctx, some (#[cstOp, newOp], #[newOp.getResult 0]))

def sub_minus_one (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite sub_minus_one_local rewriter op opInBounds

def right_identity_zero_0_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchSub op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_0 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_0_local rewriter op opInBounds

def right_identity_zero_1_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_1 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_1_local rewriter op opInBounds

def right_identity_zero_2_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchOr op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_2 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_2_local rewriter op opInBounds

def right_identity_zero_3_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchXor op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_3 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_3_local rewriter op opInBounds

def right_identity_zero_4_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchShl op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_4 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_4_local rewriter op opInBounds

def right_identity_zero_5_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchAshr op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_5 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_5_local rewriter op opInBounds

def right_identity_zero_6_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (lhs, rhs, _props) := matchLshr op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[lhs]))

def right_identity_zero_6 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_zero_6_local rewriter op opInBounds

def right_identity_one_int_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (x, rhs, _props) := matchMul op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ 1 then return (ctx, none)
  some (ctx, some (#[], #[x]))

def right_identity_one_int (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite right_identity_one_int_local rewriter op opInBounds

def binop_same_val_0_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (src, src1, _) := matchAnd op ctx.raw | return (ctx, none)
  if src != src1 then return (ctx, none)
  some (ctx, some (#[], #[src]))

def binop_same_val_0 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite binop_same_val_0_local rewriter op opInBounds

def binop_same_val_1_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (src, src1, _props) := matchOr op ctx.raw | return (ctx, none)
  if src != src1 then return (ctx, none)
  some (ctx, some (#[], #[src]))

def binop_same_val_1 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite binop_same_val_1_local rewriter op opInBounds

def same_val_zero_0_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (x, x1, _props) := matchSub op ctx.raw | return (ctx, none)
  if x != x1 then return (ctx, none)
  let .integerType type := (x.getType! ctx.raw).val | return (ctx, none)
  let cstProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (0) type))
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.mlir__constant #[x.getType! ctx.raw] #[]
    #[] #[] cstProp none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def same_val_zero_0 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite same_val_zero_0_local rewriter op opInBounds

/-- `llvm.xor x x` -> `llvm.mlir.constant 0` (64-bit only): xoring a value with itself is always
  zero (and if the operand is poison, the result poison is refined by the concrete constant). This
  is the `LocalRewritePattern` restatement of the `same_val_zero_1` MIR combine, proven correct in
  `RewriterProofs/MIRSameValZero.lean`. -/
def same_val_zero_1_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (x, x1, _props) := matchXor op ctx.raw | return (ctx, none)
  if x != x1 then return (ctx, none)
  let type := ((op.getResult 0).get! ctx.raw).type
  let .integerType type' := type.val | return (ctx, none)
  if type'.bitwidth ≠ 64 then return (ctx, none)
  let cstProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk 0 type'))
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.mlir__constant #[type] #[]
      #[] #[] cstProp none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def same_val_zero_1 (rewriter: PatternRewriter OpCode) (op: OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite same_val_zero_1_local rewriter op opInBounds

def binop_right_to_zero_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (_lhs, zero, _props) := matchMul op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal zero ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  some (ctx, some (#[], #[zero]))

def binop_right_to_zero (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite binop_right_to_zero_local rewriter op opInBounds

def mul_by_neg_one_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (x, rhs, _props) := matchMul op ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ -1 then return (ctx, none)
  let .integerType ctype := (x.getType! ctx.raw).val | return (ctx, none)
  let cstOpProp := LLVMConstantProperties.mk (.integer (IntegerAttr.mk (0) ctype))
  let (ctx, cstOp) ← WfRewriter.createOp! ctx Llvm.mlir__constant #[x.getType! ctx.raw] #[]
    #[] #[] cstOpProp none
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[x.getType! ctx.raw] #[(cstOp.getResult 0), x]
    #[] #[] _props none
  some (ctx, some (#[cstOp, newOp], #[newOp.getResult 0]))

def mul_by_neg_one (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite mul_by_neg_one_local rewriter op opInBounds

def or_and_xor_to_or_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (and, y, _props) := matchOr op ctx.raw | return (ctx, none)
  let some defOp := and.definingOp? | return (ctx, none)
  let some (x, not, _) := matchAnd defOp ctx.raw | return (ctx, none)
  let some defOp1 := not.definingOp? | return (ctx, none)
  let some (y1, rhs, _props1) := matchXor defOp1 ctx.raw | return (ctx, none)
  if y != y1 then return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ -1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.or #[and.getType! ctx.raw] #[x, y]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def or_and_xor_to_or (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite or_and_xor_to_or_local rewriter op opInBounds

def and_xor_or_to_and_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (or, y, _) := matchAnd op ctx.raw | return (ctx, none)
  let some defOp := or.definingOp? | return (ctx, none)
  let some (x, not, _props) := matchOr defOp ctx.raw | return (ctx, none)
  let some defOp1 := not.definingOp? | return (ctx, none)
  let some (y1, rhs, _props1) := matchXor defOp1 ctx.raw | return (ctx, none)
  if y != y1 then return (ctx, none)
  let some cst := matchConstantIntVal rhs ctx.raw | return (ctx, none)
  if cst.value ≠ -1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.and #[or.getType! ctx.raw] #[x, y]
    #[] #[] () none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def and_xor_or_to_and (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite and_xor_or_to_and_local rewriter op opInBounds

def add_sub_reg_0_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (x, tmp, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := tmp.definingOp? | return (ctx, none)
  let some (src, x1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  if x != x1 then return (ctx, none)
  some (ctx, some (#[], #[src]))

def add_sub_reg_0 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite add_sub_reg_0_local rewriter op opInBounds

def add_sub_reg_1_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (tmp, x, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := tmp.definingOp? | return (ctx, none)
  let some (src, x1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  if x != x1 then return (ctx, none)
  some (ctx, some (#[], #[src]))

def add_sub_reg_1 (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite add_sub_reg_1_local rewriter op opInBounds

def APlusBMinusCMinusB_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (add1, B, _props) := matchSub op ctx.raw | return (ctx, none)
  let some defOp := add1.definingOp? | return (ctx, none)
  let some (A, sub1, _props1) := matchAdd defOp ctx.raw | return (ctx, none)
  let some defOp1 := sub1.definingOp? | return (ctx, none)
  let some (B1, C, _props2) := matchSub defOp1 ctx.raw | return (ctx, none)
  if B != B1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[add1.getType! ctx.raw] #[A, C]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def APlusBMinusCMinusB (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite APlusBMinusCMinusB_local rewriter op opInBounds

def AMinusBMinusCMinusC_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (sub2, C, _props) := matchSub op ctx.raw | return (ctx, none)
  let some defOp := sub2.definingOp? | return (ctx, none)
  let some (A, sub1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some defOp1 := sub1.definingOp? | return (ctx, none)
  let some (B, C1, _props2) := matchSub defOp1 ctx.raw | return (ctx, none)
  if C != C1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[sub2.getType! ctx.raw] #[A, B]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def AMinusBMinusCMinusC (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite AMinusBMinusCMinusC_local rewriter op opInBounds

def ZeroMinusAPlusB_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (sub, B, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub.definingOp? | return (ctx, none)
  let some (lhs, A, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal lhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[sub.getType! ctx.raw] #[B, A]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def ZeroMinusAPlusB (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite ZeroMinusAPlusB_local rewriter op opInBounds

def APlusZeroMinusB_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, sub, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub.definingOp? | return (ctx, none)
  let some (lhs, B, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal lhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[A.getType! ctx.raw] #[A, B]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def APlusZeroMinusB (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite APlusZeroMinusB_local rewriter op opInBounds

def APlusBMinusB_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, sub, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub.definingOp? | return (ctx, none)
  let some (B, A1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  some (ctx, some (#[], #[B]))

def APlusBMinusB (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite APlusBMinusB_local rewriter op opInBounds

def BMinusAPlusA_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (sub, A, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub.definingOp? | return (ctx, none)
  let some (B, A1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  some (ctx, some (#[], #[B]))

def BMinusAPlusA (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite BMinusAPlusA_local rewriter op opInBounds

def AMinusBPlusCMinusA_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (sub1, sub2, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub1.definingOp? | return (ctx, none)
  let some (A, B, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some defOp1 := sub2.definingOp? | return (ctx, none)
  let some (C, A1, _props2) := matchSub defOp1 ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[sub1.getType! ctx.raw] #[C, B]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def AMinusBPlusCMinusA (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite AMinusBPlusCMinusA_local rewriter op opInBounds

def AMinusBPlusBMinusC_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (sub1, sub2, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub1.definingOp? | return (ctx, none)
  let some (A, B, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some defOp1 := sub2.definingOp? | return (ctx, none)
  let some (B1, C, _props2) := matchSub defOp1 ctx.raw | return (ctx, none)
  if B != B1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[sub1.getType! ctx.raw] #[A, C]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def AMinusBPlusBMinusC (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite AMinusBPlusBMinusC_local rewriter op opInBounds

def APlusBMinusAplusC_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, sub1, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub1.definingOp? | return (ctx, none)
  let some (B, add1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some defOp1 := add1.definingOp? | return (ctx, none)
  let some (A1, C, _props2) := matchAdd defOp1 ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[A.getType! ctx.raw] #[B, C]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def APlusBMinusAplusC (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite APlusBMinusAplusC_local rewriter op opInBounds

def APlusBMinusCPlusA_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, sub1, _props) := matchAdd op ctx.raw | return (ctx, none)
  let some defOp := sub1.definingOp? | return (ctx, none)
  let some (B, add1, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some defOp1 := add1.definingOp? | return (ctx, none)
  let some (C, A1, _props2) := matchAdd defOp1 ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.sub #[A.getType! ctx.raw] #[B, C]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def APlusBMinusCPlusA (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite APlusBMinusCPlusA_local rewriter op opInBounds

def AMinusZeroMinusB_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, sub1, _props) := matchSub op ctx.raw | return (ctx, none)
  let some defOp := sub1.definingOp? | return (ctx, none)
  let some (lhs, B, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  let some cst := matchConstantIntVal lhs ctx.raw | return (ctx, none)
  if cst.value ≠ 0 then return (ctx, none)
  let (ctx, newOp) ← WfRewriter.createOp! ctx Llvm.add #[A.getType! ctx.raw] #[A, B]
    #[] #[] _props none
  some (ctx, some (#[newOp], #[newOp.getResult 0]))

def AMinusZeroMinusB (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite AMinusZeroMinusB_local rewriter op opInBounds

def AMinusBMinusA_local (ctx : WfIRContext OpCode) (op : OperationPtr) :
    Option (WfIRContext OpCode × Option (Array OperationPtr × Array ValuePtr)) := do
  let some (A, add, _props) := matchSub op ctx.raw | return (ctx, none)
  let some defOp := add.definingOp? | return (ctx, none)
  let some (A1, B, _props1) := matchSub defOp ctx.raw | return (ctx, none)
  if A != A1 then return (ctx, none)
  some (ctx, some (#[], #[B]))

def AMinusBMinusA (rewriter : PatternRewriter OpCode) (op : OperationPtr)
    (opInBounds : op.InBounds rewriter.ctx.raw) : Option (PatternRewriter OpCode) :=
  RewritePattern.fromLocalRewrite AMinusBMinusA_local rewriter op opInBounds

def mir_pattern_combines :=
  [sub_minus_one,
  right_identity_zero_0,
  right_identity_zero_1,
  right_identity_zero_2,
  right_identity_zero_3,
  right_identity_zero_4,
  right_identity_zero_5,
  right_identity_zero_6,
  right_identity_one_int,
  binop_same_val_0,
  binop_same_val_1,
  same_val_zero_0,
  same_val_zero_1,
  binop_right_to_zero,
  mul_by_neg_one,
  or_and_xor_to_or,
  and_xor_or_to_and,
  add_sub_reg_0,
  add_sub_reg_1,
  APlusBMinusCMinusB,
  AMinusBMinusCMinusC,
  ZeroMinusAPlusB,
  APlusZeroMinusB,
  APlusBMinusB,
  BMinusAPlusA,
  AMinusBPlusCMinusA,
  AMinusBPlusBMinusC,
  APlusBMinusAplusC,
  APlusBMinusCPlusA,
  AMinusZeroMinusB,
  AMinusBMinusA]

end Veir.RISCV
