name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Source environment variables
        run: source .envrc

      - name: Add LLVM apt repository
        uses: gerlero/add-apt-repository@v1
        with:
          uri: http://apt.llvm.org/noble/
          key: https://apt.llvm.org/llvm-snapshot.gpg.key
          component: main
          suite: llvm-toolchain-noble-22

      - name: Install mlir-opt
        uses: gerlero/apt-install@v1
        with:
          packages: mlir-22-tools

      - name: Rename MLIR-opt
        run: |
          sudo ln -s /usr/bin/mlir-opt-22 /usr/bin/mlir-opt

      - name: Build the project
        uses: leanprover/lean-action@v1
        with:
          build-args: "--iofail"
          test: false

      - name: Run unit tests
        uses: leanprover/lean-action@v1
        with:
          test-args: "--iofail"
          test: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: uv sync

      - name: Run filecheck tests
        run: uv run lit Test/ -v

      - name: Build the ExArray package
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "ExArray"

      - name: Run the ExArray test binary
        run: |
          pushd ExArray
          lake exe test
          popd
