// RUN: veir2mir %s | filecheck %s

// A straight-line `main : i64 ()` already lowered to the riscv dialect (the
// output of vsmith --riscv).  Checks that veir2mir lowers the immediate,
// reg-imm, and reg-reg forms, turns the result cast into a COPY, and emits the
// return sequence into $x10.  Generated by Tools/vsmith --riscv.

"builtin.module"() ({
  ^4():
    "llvm.func"() <{"function_type" = !llvm.func<i64 ()>, "sym_name" = "main"}> ({
      ^6():
        %79 = "riscv.li"() <{"value" = 1 : i64}> : () -> !riscv.reg
        %77 = "riscv.li"() <{"value" = 140737488355327 : i64}> : () -> !riscv.reg
        %39 = "riscv.andi"(%77) <{"value" = 1 : i64}> : (!riscv.reg) -> !riscv.reg
        %75 = "riscv.li"() <{"value" = -67109378 : i64}> : () -> !riscv.reg
        %73 = "riscv.li"() <{"value" = 3458764516236460031 : i64}> : () -> !riscv.reg
        %71 = "riscv.rem"(%75, %73) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %36 = "riscv.ori"(%79) <{"value" = 1 : i64}> : (!riscv.reg) -> !riscv.reg
        %67 = "riscv.divu"(%71, %36) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %63 = "riscv.xor"(%71, %39) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %33 = "riscv.xori"(%63) <{"value" = 1 : i64}> : (!riscv.reg) -> !riscv.reg
        %59 = "riscv.xor"(%36, %33) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %55 = "riscv.xor"(%75, %59) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %51 = "riscv.xor"(%73, %55) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %47 = "riscv.xor"(%77, %51) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %30 = "riscv.xori"(%47) <{"value" = 1 : i64}> : (!riscv.reg) -> !riscv.reg
        %43 = "riscv.xor"(%67, %30) : (!riscv.reg, !riscv.reg) -> !riscv.reg
        %44 = "builtin.unrealized_conversion_cast"(%43) : (!riscv.reg) -> i64
        "llvm.return"(%44) : (i64) -> ()
    }) : () -> ()
}) : () -> ()

// CHECK: name:            main
// CHECK: body:
// CHECK: bb.0:
// CHECK-NOT: successors:
// CHECK: PseudoLI 1
// CHECK: PseudoLI 140737488355327
// CHECK: ANDI {{.*}}, 1
// CHECK: PseudoLI -67109378
// CHECK: PseudoLI 3458764516236460031
// CHECK: REM
// CHECK: ORI {{.*}}, 1
// CHECK: DIVU
// CHECK: XOR
// CHECK: XORI {{.*}}, 1
// A reg<->i64 cast becomes a COPY.
// CHECK: [[RET:%[a-z0-9]+]]:gpr = COPY
// CHECK: $x10 = COPY [[RET]]
// CHECK: PseudoRET implicit $x10
